export const images = {
  calender: "/assets/icons/calendar.svg",
  people: "/assets/icons/users.svg",
  layout: "/assets/icons/layout-dashboard.svg",
  expand: "/assets/icons/chevron-down.svg",
  search: "/assets/icons/search.svg",
  logo: "/assets/icons/logo.svg",
  frame: "/assets/icons/Frame 48098411.svg",
  arrow_lr: "/assets/icons/arrow-left-right.svg",
  globe: "/assets/icons/globe.svg",
  orders: "/assets/icons/inbox.svg",
  hourglass: "/assets/icons/hourglass.svg",
  calenderDays: "/assets/icons/calendar-days.svg",
  subscription: "/assets/icons/subscription.svg",
  redirect: "/assets/icons/secondary icon.svg",
  profileImage: "/assets/profileImages/Ellipse 1.png",
  help: "/assets/icons/help-circle.svg",
  filter: "/assets/icons/filter.svg",
  refresh: "/assets/icons/refresh-ccw.svg",
  column: "/assets/icons/columns.svg",
  download: "/assets/icons/download.svg",
  user: "/assets/icons/user.svg",
  circleDot: "/assets/icons/circle-dot.svg",
  hash: "/assets/icons/hash.svg",
  updown: "/assets/icons/chevrons-up-down.svg",
  left: "/assets/icons/chevron-left.svg",
  right: "/assets/icons/chevron-right.svg",
  amount: "/assets/icons/bag-3-svgrepo-com.svg",
  transaction: "/assets/icons/arrow-left-right.svg",
  address: "/assets/icons/address-location-map-svgrepo-com.svg",
  check:"/assets/icons/check.svg"
};
