import { Input } from "postcss";
import { images } from "./images";

export interface Person {
  name: string;
  type: "Payer" | "Attendee";
}
export const sidebar = [
  {
    icon: images.calender,
    label: "schedule date",
  },
  {
    icon: images.people,
    label: "people",
  },
  {
    icon: images.layout,
    label: "services/products",
  },
];

export const dateItem = [
  {
    label: "from",
    icon: images.calender,
  },
  {
    label: "to",
    icon: images.calender,
  },
];

export const dropdownMenu = [
  "all",
  "custom",
  "last 30 days",
  " this month",
  "last month",
  "this quarter",
  "2 quarter ago",
  "this year",
  "last year",
];

export const people: Person[] = [
  { name: "Alice", type: "Payer" },
  { name: "Aiden", type: "Attendee" },
  { name: "Ava", type: "Payer" },
  { name: "Amelia", type: "Attendee" },
  { name: "Arthur", type: "Payer" },
  { name: "Ben", type: "Attendee" },
  { name: "Bella", type: "Payer" },
  { name: "Brooke", type: "Attendee" },
  { name: "Bryan", type: "Payer" },
  { name: "Blake", type: "Attendee" },
  { name: "Charlotte", type: "Payer" },
  { name: "Caleb", type: "Attendee" },
  { name: "Chloe", type: "Payer" },
  { name: "Cameron", type: "Attendee" },
  { name: "Carson", type: "Payer" },
  { name: "Daniel", type: "Attendee" },
  { name: "Daisy", type: "Payer" },
  { name: "David", type: "Attendee" },
  { name: "Dylan", type: "Payer" },
  { name: "Delilah", type: "Attendee" },
  { name: "Ella", type: "Payer" },
  { name: "Ethan", type: "Attendee" },
  { name: "Evelyn", type: "Payer" },
  { name: "Elijah", type: "Attendee" },
  { name: "Emma", type: "Payer" },
  { name: "Fiona", type: "Attendee" },
  { name: "Felix", type: "Payer" },
  { name: "Faith", type: "Attendee" },
  { name: "Finn", type: "Payer" },
  { name: "Freya", type: "Attendee" },
  { name: "Grace", type: "Payer" },
  { name: "Gabriel", type: "Attendee" },
  { name: "Gavin", type: "Payer" },
  { name: "Gemma", type: "Attendee" },
  { name: "Georgia", type: "Payer" },
  { name: "Henry", type: "Attendee" },
  { name: "Hannah", type: "Payer" },
  { name: "Hazel", type: "Attendee" },
  { name: "Hugo", type: "Payer" },
  { name: "Harper", type: "Attendee" },
  { name: "Isla", type: "Payer" },
  { name: "Isaac", type: "Attendee" },
  { name: "Ivy", type: "Payer" },
  { name: "Ian", type: "Attendee" },
  { name: "Isabelle", type: "Payer" },
  { name: "Jack", type: "Attendee" },
  { name: "Julia", type: "Payer" },
  { name: "James", type: "Attendee" },
  { name: "Jade", type: "Payer" },
  { name: "Jasper", type: "Attendee" },
  { name: "Kai", type: "Payer" },
  { name: "Kara", type: "Attendee" },
  { name: "Kieran", type: "Payer" },
  { name: "Kylie", type: "Attendee" },
  { name: "Kevin", type: "Payer" },
  { name: "Liam", type: "Attendee" },
  { name: "Luna", type: "Payer" },
  { name: "Leo", type: "Attendee" },
  { name: "Layla", type: "Payer" },
  { name: "Lucas", type: "Attendee" },
  { name: "Mia", type: "Payer" },
  { name: "Mason", type: "Attendee" },
  { name: "Mila", type: "Payer" },
  { name: "Michael", type: "Attendee" },
  { name: "Madison", type: "Payer" },
  { name: "Noah", type: "Attendee" },
  { name: "Nora", type: "Payer" },
  { name: "Nathan", type: "Attendee" },
  { name: "Natalie", type: "Payer" },
  { name: "Nicholas", type: "Attendee" },
  { name: "Olivia", type: "Payer" },
  { name: "Owen", type: "Attendee" },
  { name: "Oscar", type: "Payer" },
  { name: "Ophelia", type: "Attendee" },
  { name: "Oliver", type: "Payer" },
  { name: "Penelope", type: "Attendee" },
  { name: "Parker", type: "Payer" },
  { name: "Paisley", type: "Attendee" },
  { name: "Patrick", type: "Payer" },
  { name: "Paige", type: "Attendee" },
  { name: "Quinn", type: "Payer" },
  { name: "Quincy", type: "Attendee" },
  { name: "Quentin", type: "Payer" },
  { name: "Quiana", type: "Attendee" },
  { name: "Ryan", type: "Payer" },
  { name: "Ruby", type: "Attendee" },
  { name: "Riley", type: "Payer" },
  { name: "Rebecca", type: "Attendee" },
  { name: "Ronan", type: "Payer" },
  { name: "Sophia", type: "Attendee" },
  { name: "Samuel", type: "Payer" },
  { name: "Scarlett", type: "Attendee" },
  { name: "Sebastian", type: "Payer" },
  { name: "Stella", type: "Attendee" },
  { name: "Thomas", type: "Payer" },
  { name: "Tessa", type: "Attendee" },
  { name: "Theo", type: "Payer" },
  { name: "Taylor", type: "Attendee" },
  { name: "Tristan", type: "Payer" },
  { name: "Uma", type: "Attendee" },
  { name: "Ulysses", type: "Payer" },
  { name: "Uri", type: "Attendee" },
  { name: "Ulrich", type: "Payer" },
  { name: "Ursula", type: "Attendee" },
  { name: "Violet", type: "Payer" },
  { name: "Victor", type: "Attendee" },
  { name: "Valerie", type: "Payer" },
  { name: "Vincent", type: "Attendee" },
  { name: "Vanessa", type: "Payer" },
  { name: "William", type: "Attendee" },
  { name: "Willa", type: "Payer" },
  { name: "Wyatt", type: "Attendee" },
  { name: "Wren", type: "Payer" },
  { name: "Wesley", type: "Attendee" },
  { name: "Xander", type: "Payer" },
  { name: "Xena", type: "Attendee" },
  { name: "Xavier", type: "Payer" },
  { name: "Ximena", type: "Attendee" },
  { name: "Xia", type: "Payer" },
  { name: "Yara", type: "Attendee" },
  { name: "Yosef", type: "Payer" },
  { name: "Yasmine", type: "Attendee" },
  { name: "Yvonne", type: "Payer" },
  { name: "Yuri", type: "Attendee" },
  { name: "Zoe", type: "Payer" },
  { name: "Zachary", type: "Attendee" },
  { name: "Zara", type: "Payer" },
  { name: "Zane", type: "Attendee" },
  { name: "Zelda", type: "Payer" },
];

export const service = ["Search by name", "Search by tags"];
export const dashboardMenu = [
  {
    icon: images.orders,
    label: "orders",
  },
  {
    icon: images.subscription,
    label: "subscriptions",
  },
  {
    icon: images.calenderDays,
    label: "calender",
  },
  {
    icon: images.hourglass,
    label: "waitlist",
  },
];

export const dheader = [
  {
    label: "all waitlist",
    count: 100,
  },
  {
    label: "newly added",
    count: 50,
  },
  {
    label: "leads",
    count: 20,
  },
];
